# Generated by Django 4.2.5 on 2023-09-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_alter_location_options_alter_location_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
